
services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    working_dir: /code
    volumes:
      - ./:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  
  php:
    build:
      context: ./docker/php
    image: php:8-fpm
    container_name: php
    working_dir: /code
    volumes:
      - ./:/code
  
  database:
      image: postgres:16-alpine
      restart: always
      container_name: ${DATABASE_CONTAINER_NAME}
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=${DATABASE_NAME}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_USER=${DATABASE_USER}
      volumes:
        - db_data:/var/lib/postgresql/data:rw

  pgAdmin:
      restart: always
      image: dpage/pgadmin4
      container_name: pgadmin
      ports:
        - "5000:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: test@test.com
        PGADMIN_DEFAULT_PASSWORD: test
      volumes:
        - pgadmin_data:/var/lib/pgadmin
      depends_on:
        - database
volumes:
  db_data:
  pgadmin_data: